{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6cfd2d08-5341-40b1-b902-5c591a2b1082",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Load the datasets (replace 'path_to_your_dataset.csv' with the actual paths)\n",
    "financial_ledger_df = pd.read_csv('FinLedger.csv')\n",
    "useeio_df = pd.read_csv('useeio.csv')\n",
    "\n",
    "# Display initial information about the datasets\n",
    "print(\"Financial Ledger Dataset Info:\")\n",
    "print(financial_ledger_df.info())\n",
    "print(\"\\nUSEEIO Dataset Info:\")\n",
    "print(useeio_df.info())\n",
    "\n",
    "# Data Cleaning for Financial Ledger Transactions\n",
    "\n",
    "# 1. Identify and remove duplicate entries\n",
    "financial_ledger_df = financial_ledger_df.drop_duplicates()\n",
    "\n",
    "# 2. Identify and remove irrelevant entries\n",
    "# Example criteria: Filter based on date range and relevance to scope 3 emissions\n",
    "date_column = 'transaction_date'\n",
    "start_date = '2020-01-01'\n",
    "end_date = '2023-12-31'\n",
    "relevant_criteria = 'Scope 3'  # This could be a column indicating relevance to scope 3 emissions\n",
    "\n",
    "financial_ledger_df[date_column] = pd.to_datetime(financial_ledger_df[date_column])\n",
    "financial_ledger_df = financial_ledger_df[\n",
    "    (financial_ledger_df[date_column] >= start_date) &\n",
    "    (financial_ledger_df[date_column] <= end_date) &\n",
    "    (financial_ledger_df['emission_scope'] == relevant_criteria)\n",
    "]\n",
    "\n",
    "# 3. Additional filtering based on data quality if needed\n",
    "financial_ledger_df = financial_ledger_df.dropna(subset=['amount', 'emission_factor'])\n",
    "\n",
    "# Data Cleaning for USEEIO Dataset\n",
    "\n",
    "# 1. Identify and remove duplicate entries\n",
    "useeio_df = useeio_df.drop_duplicates()\n",
    "\n",
    "# 2. Identify and remove irrelevant entries\n",
    "# Example criteria: Filter based on relevance to scope 3 emissions\n",
    "relevant_column = 'emission_type'\n",
    "relevant_value = 'Scope 3'\n",
    "\n",
    "useeio_df = useeio_df[useeio_df[relevant_column] == relevant_value]\n",
    "\n",
    "# 3. Additional filtering based on data quality if needed\n",
    "# Example: Remove rows with missing values in critical columns\n",
    "useeio_df = useeio_df.dropna(subset=['emission_factor', 'sector'])\n",
    "\n",
    "# Display cleaned datasets information\n",
    "print(\"\\nCleaned Financial Ledger Dataset Info:\")\n",
    "print(financial_ledger_df.info())\n",
    "print(\"\\nCleaned USEEIO Dataset Info:\")\n",
    "print(useeio_df.info())\n",
    "\n",
    "# Save the cleaned datasets\n",
    "financial_ledger_df.to_csv('cleaned_financial_ledger.csv', index=False)\n",
    "useeio_df.to_csv('cleaned_useeio.csv', index=False)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
