{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "277ca455-9224-4cc0-bbe6-e6d084c9f9dd",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.stats import pearsonr\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "# Load the USEEIO dataset\n",
    "\n",
    "useeio_df = pd.read_csv('useeio.csv')\n",
    "\n",
    "# Assuming the dataset has the following columns:\n",
    "# 'commodity', 'emission_factor', 'reliability_score', 'technological_correlation',\n",
    "# 'data_collection', 'geographical_correlation', 'temporal_correlation',\n",
    "# 'emission_factor_with_margin'\n",
    "\n",
    "# Display initial information about the dataset\n",
    "print(\"USEEIO Dataset Info:\")\n",
    "print(useeio_df.info())\n",
    "\n",
    "# 4.3.1 Correlation Analysis\n",
    "# Calculate correlations between emission factors and data quality scores\n",
    "data_quality_columns = ['reliability_score', 'technological_correlation', 'data_collection', 'geographical_correlation', 'temporal_correlation']\n",
    "correlations = {}\n",
    "\n",
    "for column in data_quality_columns:\n",
    "    correlation, _ = pearsonr(useeio_df['emission_factor'], useeio_df[column])\n",
    "    correlations[column] = correlation\n",
    "\n",
    "# Plot the correlations\n",
    "plt.figure(figsize=(10, 6))\n",
    "sns.barplot(x=list(correlations.keys()), y=list(correlations.values()), palette='viridis')\n",
    "plt.title('Correlation between Emission Factors and Data Quality Scores')\n",
    "plt.xlabel('Data Quality Scores')\n",
    "plt.ylabel('Pearson Correlation Coefficient')\n",
    "plt.tight_layout()\n",
    "plt.savefig('correlation_analysis.png')\n",
    "plt.show()\n",
    "\n",
    "# 4.3.2 Comparison between emission factors with and without margins\n",
    "useeio_df['difference'] = useeio_df['emission_factor_with_margin'] - useeio_df['emission_factor']\n",
    "\n",
    "# Summary statistics\n",
    "positive_diff = useeio_df[useeio_df['difference'] > 0].shape[0]\n",
    "no_diff = useeio_df[useeio_df['difference'] == 0].shape[0]\n",
    "negative_diff = useeio_df[useeio_df['difference'] < 0].shape[0]\n",
    "\n",
    "print(f\"Positive Difference: {positive_diff}\")\n",
    "print(f\"No Difference: {no_diff}\")\n",
    "print(f\"Negative Difference: {negative_diff}\")\n",
    "\n",
    "# Visualization\n",
    "plt.figure(figsize=(10, 6))\n",
    "sns.histplot(useeio_df['difference'], bins=20, kde=True)\n",
    "plt.title('Distribution of Differences between Emission Factors with and without Margins')\n",
    "plt.xlabel('Difference in Emission Factors')\n",
    "plt.ylabel('Frequency')\n",
    "plt.tight_layout()\n",
    "plt.savefig('emission_factors_comparison.png')\n",
    "plt.show()\n",
    "\n",
    "# 4.3.3 Analysis of substance distribution\n",
    "# Assuming we have columns 'co2_emissions', 'ch4_emissions', 'n2o_emissions', 'other_ghg_emissions'\n",
    "substances = ['co2_emissions', 'ch4_emissions', 'n2o_emissions', 'other_ghg_emissions']\n",
    "useeio_df[substances] = useeio_df[substances].fillna(0)  # Fill NaN with 0\n",
    "\n",
    "# Grouping by commodity and calculating total emissions for each greenhouse gas\n",
    "total_emissions = useeio_df.groupby('commodity')[substances].sum().reset_index()\n",
    "\n",
    "# Visualization\n",
    "total_emissions.set_index('commodity').plot(kind='bar', stacked=True, figsize=(12, 8), colormap='viridis')\n",
    "plt.title('Distribution of Greenhouse Gas Emissions across Different Commodities')\n",
    "plt.xlabel('Commodity')\n",
    "plt.ylabel('Total Emissions')\n",
    "plt.xticks(rotation=90)\n",
    "plt.tight_layout()\n",
    "plt.savefig('substance_distribution.png')\n",
    "plt.show()\n",
    "\n",
    "# 4.3.4 Comparison between detail and summary categories\n",
    "# Assuming we have a 'category' column indicating detail or summary\n",
    "detailed_df = useeio_df[useeio_df['category'] == 'detail']\n",
    "summary_df = useeio_df[useeio_df['category'] == 'summary']\n",
    "\n",
    "# Calculating mean emission factors and data quality scores\n",
    "detail_means = detailed_df[data_quality_columns + ['emission_factor']].mean()\n",
    "summary_means = summary_df[data_quality_columns + ['emission_factor']].mean()\n",
    "\n",
    "# Visualization\n",
    "mean_df = pd.DataFrame({'Detail': detail_means, 'Summary': summary_means})\n",
    "mean_df.plot(kind='bar', figsize=(10, 6), colormap='viridis')\n",
    "plt.title('Comparison of Mean Emission Factors and Data Quality Scores')\n",
    "plt.xlabel('Metrics')\n",
    "plt.ylabel('Mean Values')\n",
    "plt.tight_layout()\n",
    "plt.savefig('detail_summary_comparison.png')\n",
    "plt.show()\n",
    "\n",
    "# 4.3.5 Outlier Detection based on Data Quality Scores\n",
    "# Standardizing the data quality scores for outlier detection\n",
    "scaler = StandardScaler()\n",
    "scaled_data_quality = scaler.fit_transform(useeio_df[data_quality_columns])\n",
    "\n",
    "# Detecting outliers using z-score method (threshold = 3)\n",
    "z_scores = np.abs(scaled_data_quality)\n",
    "outliers = (z_scores > 3).any(axis=1)\n",
    "\n",
    "# Filtering outliers\n",
    "outlier_df = useeio_df[outliers]\n",
    "\n",
    "# Visualization of outliers\n",
    "plt.figure(figsize=(10, 6))\n",
    "plt.scatter(useeio_df['reliability_score'], useeio_df['emission_factor'], label='Normal Data', alpha=0.5)\n",
    "plt.scatter(outlier_df['reliability_score'], outlier_df['emission_factor'], color='red', label='Outliers')\n",
    "plt.title('Outliers based on Reliability Score and Emission Factors')\n",
    "plt.xlabel('Reliability Score')\n",
    "plt.ylabel('Emission Factor')\n",
    "plt.legend()\n",
    "plt.tight_layout()\n",
    "plt.savefig('outlier_detection.png')\n",
    "plt.show()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
